In [4]:
#large scale ml
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
x, y = make_classification(n_samples=50000, n_features=10,
                           n_classes=3,
                           n_clusters_per_class=1)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.15)
train_data = np.concatenate((xtrain, ytrain[:, np.newaxis]), axis=1)
a = np.asarray(train_data)
np.savetxt("train_data.csv", a, delimiter=",")

In [5]:
clf=SGDClassifier(max_iter=1000, tol=0.01)
chunksize=1000
iter=1
for traindf in pd.read_csv("train_data.csv",chunksize=chunksize,iterator=True):
    if iter==1:
        xtrain_partial= traindf.iloc[:, 0:10]
        ytrain_partial=traindf.iloc[:, 10]
        clf.partial_fit(xtrain_partial, ytrain_partial, classes=np.array([0,1,2]))
    else:
        xtrain_partial= traindf.iloc[:, 0:10]
        ytrain_partial=traindf.iloc[:, 10]
        clf.partial_fit(xtrain_partial, ytrain_partial)
    print("----------------------- After iter",iter,"-----------------------")
    print("-----coef-----", clf.coef_)
    print("-----intercept-----", clf.intercept_)
    iter+=1

----------------------- After iter 1 -----------------------
-----coef----- [[  4.73826932   7.15064472  20.3184982   -3.10421022  70.11517395
   -2.99383993 -16.12289948 -17.79226845   6.07358773  -7.86013283]
 [ -0.82531212   6.72102575  -3.13371723  17.0880692  -32.0686532
  -19.64637095 -10.17550267  -1.01104738  14.36726961   6.52023809]
 [  8.85100846   4.32617023 -10.87476659 -21.61773911  19.98513354
   26.95546102  18.62687014  -4.13186058  -4.56778888   5.32850002]]
-----intercept----- [-51.0597056  -49.27505067 -25.17566641]
----------------------- After iter 2 -----------------------
-----coef----- [[ -1.98326295  -0.24373145  -4.48923975  -0.76433583  57.1338488
   -4.80712593 -15.11496061  -1.26402035   1.62759487  -2.4876584 ]
 [  0.16444118  -4.88762002  -7.24117938  21.99745038 -31.8118003
  -26.25747657 -15.7461739    3.90932726  10.23255645   3.60756284]
 [ 17.64958543  -2.49079109   8.60103622  -9.49784391 -12.83610835
   14.04965923  14.22646793   1.41729475   0.68

----------------------- After iter 22 -----------------------
-----coef----- [[-0.7854756   1.29154941 -0.78524244 -1.43564043  9.8116954   0.9240105
  -1.13471648 -1.17928011 -0.58204012  1.61808579]
 [-0.95038002  0.81038874  0.27935411  3.3088167  -6.46792216 -3.77781412
  -1.89809109 -0.04408059  0.21082084  0.87550503]
 [ 1.4256148  -1.6408864  -1.36410746 -2.65689384  1.8163951   3.37823461
   2.46816701  0.11638799 -0.58956804 -0.6757772 ]]
-----intercept----- [-4.27694242 -6.96288452 -0.32843656]
----------------------- After iter 23 -----------------------
-----coef----- [[-0.13256983  0.6008198  -2.34712097 -0.39521297  7.00939793 -0.18543735
  -1.5167242   0.17247044  1.38167544  0.83643215]
 [-0.13456034 -0.98551012 -1.0028313   3.0053845  -6.09645155 -3.40874501
  -1.66206461 -0.25607976  1.25976584 -0.29829476]
 [-1.13521085 -0.17981838 -0.55608355 -2.85744528 -0.10305517  3.8431722
   3.2293585  -0.38235502  0.24032468 -1.21329822]]
-----intercept----- [-3.88490407 -6.56

----------------------- After iter 42 -----------------------
-----coef----- [[-0.2021503   0.74513351  0.11840485 -0.50232223  6.42176854  0.01821302
  -1.23248923 -0.46043921 -0.24381728  0.90149711]
 [-0.08674412  0.56079194 -0.51301308  1.67892103 -3.0135474  -1.94428578
  -1.03811553  1.09014167  1.02570959  0.24327342]
 [-0.59360023 -0.36662953 -0.54622954 -1.45860856 -0.87009228  2.04523214
   1.87697352 -0.77917839 -0.60562273  0.13663478]]
-----intercept----- [-2.92726012 -4.71485959 -0.8088282 ]
----------------------- After iter 43 -----------------------
-----coef----- [[ 0.89852383 -1.41814165  0.0516862  -0.09958612  6.46767233 -0.52665734
  -1.6964154  -0.13556713  0.32962724  0.18087887]
 [ 0.53366563 -0.11865985 -0.42050468  2.00507709 -4.13301517 -2.26747728
  -1.09050089 -0.58003631 -0.03962243  0.51357116]
 [-0.13876218 -0.66536895  0.56617622 -1.41840887  0.05714724  1.89665868
   1.57274834 -0.54410062  0.25063984  0.82985562]]
-----intercept----- [-3.16100457 -4.

In [7]:
ypred = clf.predict(xtest)
cm = confusion_matrix(ytest, ypred)
print(cm)
cr = classification_report(ytest, ypred)
print(cr)

[[2437    9   33]
 [ 110 2099  259]
 [  11  332 2210]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      2479
           1       0.86      0.85      0.86      2468
           2       0.88      0.87      0.87      2553

    accuracy                           0.90      7500
   macro avg       0.90      0.90      0.90      7500
weighted avg       0.90      0.90      0.90      7500



In [9]:
#large scale preprocessing
text_documents = ['The well-known saying an apple a day keeps the doctor away has a very straightforward, literal meaning, that the eating of fruit maintains good health.',
                  'The proverb first appeared in print in 1866 and over 150 years later is advice that we still pass down through generations.',
                  'British apples are one of the nations best loved fruit and according to Great British Apples, we consume around 122,000 tonnes of them each year.',
                  'But what are the health benefits, and do they really keep the doctor away?']

from sklearn.feature_extraction.text import CountVectorizer
c_vectorizer = CountVectorizer()
X_c = c_vectorizer.fit_transform(text_documents)
print(c_vectorizer.vocabulary_)

{'the': 54, 'well': 62, 'known': 36, 'saying': 50, 'an': 6, 'apple': 9, 'day': 19, 'keeps': 35, 'doctor': 21, 'away': 13, 'has': 30, 'very': 60, 'straightforward': 52, 'literal': 38, 'meaning': 41, 'that': 53, 'eating': 24, 'of': 43, 'fruit': 26, 'maintains': 40, 'good': 28, 'health': 31, 'proverb': 48, 'first': 25, 'appeared': 8, 'in': 32, 'print': 47, '1866': 3, 'and': 7, 'over': 45, '150': 2, 'years': 65, 'later': 37, 'is': 33, 'advice': 5, 'we': 61, 'still': 51, 'pass': 46, 'down': 22, 'through': 57, 'generations': 27, 'british': 16, 'apples': 10, 'are': 11, 'one': 44, 'nations': 42, 'best': 15, 'loved': 39, 'according': 4, 'to': 58, 'great': 29, 'consume': 18, 'around': 12, '122': 1, '000': 0, 'tonnes': 59, 'them': 55, 'each': 23, 'year': 64, 'but': 17, 'what': 63, 'benefits': 14, 'do': 20, 'they': 56, 'really': 49, 'keep': 34}


In [11]:
from sklearn.feature_extraction.text import HashingVectorizer
h_vectorizer= HashingVectorizer(n_features=50)
X_h = h_vectorizer.fit_transform(text_documents)
print(X_h[0])

  (0, 5)	0.0
  (0, 8)	-0.47140452079103173
  (0, 10)	-0.23570226039551587
  (0, 11)	-0.23570226039551587
  (0, 13)	0.0
  (0, 18)	-0.23570226039551587
  (0, 20)	0.23570226039551587
  (0, 26)	0.0
  (0, 29)	0.23570226039551587
  (0, 33)	0.23570226039551587
  (0, 36)	-0.23570226039551587
  (0, 38)	0.47140452079103173
  (0, 39)	-0.23570226039551587
  (0, 45)	-0.23570226039551587
  (0, 46)	0.23570226039551587


In [12]:
#combining the fit and preproc
import pandas as pd
from io import StringIO, BytesIO, TextIOWrapper
from zipfile import ZipFile
import urllib.request

resp = urllib.request.urlopen('https://archive.ics.uci.edu/ml/machine-learning-databases/00331/sentiment%20labelled%20sentences.zip')
zipfile = ZipFile(BytesIO(resp.read()))

data = TextIOWrapper(zipfile.open('sentiment labelled sentences/amazon_cells_labelled.txt'), encoding='utf-8')

df = pd.read_csv(data, sep = '\t')
df.columns = ['review', 'sentiment']

In [13]:
df.tail()

review  sentiment
994  The screen does get smudged easily because it ...          0
995  What a piece of junk.. I lose more calls on th...          0
996                       Item Does Not Match Picture.          0
997  The only thing that disappoint me is the infra...          0
998  You can not answer calls with the unit, never ...          0

In [14]:
X = df.loc[:, 'review']
y= df.loc[:, 'sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
vectorizer = HashingVectorizer()
classifier = SGDClassifier(penalty='l2',loss='hinge')
X_train_part1_hashed = vectorizer.fit_transform(X_train[0:400])
y_train_part1 = y_train[0:400]
all_classes = np.unique(df.loc[:, 'sentiment'])
classifier.partial_fit(X_train_part1_hashed, y_train_part1, classes=all_classes)

SGDClassifier()

In [17]:
X_test_hashed = vectorizer.transform(X_test)
test_score = classifier.score(X_test_hashed, y_test)
print("Test score: ", test_score)

Test score:  0.75


In [18]:
X_train_part2_hashed = vectorizer.fit_transform(X_train[400:])
y_train_part2 = y_train[400:]
classifier.partial_fit(X_train_part2_hashed, y_train_part2)
test_score = classifier.score(X_test_hashed, y_test)
print("Test score: ", test_score)

Test score:  0.79
